# Generated by Django 4.0.3 on 2023-12-26 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolstedParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Уник. операторов', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Уник. операндов', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Общ. операторов', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Общ. операндов', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Входные/выходные переменные', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
