# Generated by Django 4.0.3 on 2023-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChepinParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param1",
                    models.IntegerField(
                        verbose_name="Вводимые переменные для расчетов и для обеспечения вывода"
                    ),
                ),
                ("param2", models.IntegerField(verbose_name="Весовой коэффициент 1")),
                (
                    "param3",
                    models.IntegerField(
                        verbose_name="Модифицируемые, или создаваемые внутри программы переменные"
                    ),
                ),
                ("param4", models.IntegerField(verbose_name="Весовой коэффициент 2")),
                (
                    "param5",
                    models.IntegerField(
                        verbose_name="Переменные, участвующие в управлении работой программного модуля"
                    ),
                ),
                ("param6", models.IntegerField(verbose_name="Весовой коэффициент 3")),
                (
                    "param7",
                    models.IntegerField(
                        verbose_name="Не используемые в программе («паразитные») переменные"
                    ),
                ),
                ("param8", models.IntegerField(verbose_name="Весовой коэффициент 4")),
            ],
        ),
    ]
